project:
  type: book

book:
  title: "Assesing uncertanties related to satellite remote sensing indices to estimate Gross Primary Production"
  author: "Ronny A. Hernández Mora"
  date: "2023"
  chapters:
    - abstract.qmd
    - index.qmd
    - dedication.qmd
    - acknowledgements.qmd
    - list_abbreviations.qmd
    - chapter_1_intro.qmd
    - chapter_2_lm.qmd
    - chapter_3_ml.qmd
    - chapter_4_conclusions.qmd
    - bibliography.qmd
    - appendices.qmd

bibliography: 
 - rap_v002.bib

format:
  pdf:
    tbl-cap-location: top
    documentclass: scrreprt
    lof: true
    lot: true
    page-breaks: true
    filters:
     - section-refs.lua # needs pandoc version >= 2.11 to work


    

