project:
  type: book

book:
  title: "Assesing uncertanties related to satellite remote sensing indices to estimate Gross Primary Production"
  subtitle: "By"
  author: 
    - name: "Ronny A. Hernández Mora"
      orcid: "0000-0001-6225-7096"
      affiliations:
        - name: "University of Alberta"
          department: "Department of Earth and Atmospheric Sciences"
  date: "01 September 2023"
  date-format: "MMMM YYYY"
  chapters:
    - abstract.qmd
    - index.qmd
    - dedication.qmd
    - acknowledgements.qmd
    - list_abbreviations.qmd
    - chapter_1_intro.qmd
    - chapter_2_lm.qmd
    - chapter_3_ml.qmd
    - chapter_4_conclusions.qmd
    - bibliography.qmd
    - appendices.qmd

bibliography: 
 - rap_v002.bib

format:
  pdf:
    template-partials:
      - before-body.tex
    tbl-cap-location: top
    documentclass: scrreprt
    lof: true
    lot: true
    page-breaks: true
    geometry:
      - inner=3cm
      - outer=4cm
      - top=3cm
      - bottom=4cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    filters:
     - section-refs.lua # needs pandoc version >= 2.11 to work


    

