# Abstract {.unnumbered}

Methods to quantify Gross Primary Production (GPP) are classified into two
categories: Eddy Covariance techniques (EC) and satellite data-driven. EC
techniques can measure carbon fluxes directly, albeit with spatial constraints.
Satellite data-driven methods are promising because they overcome spatial
constraints associated with EC techniques. However, satellite-driven products
have potentially greater uncertainty than EC methods for GPP estimation such as
mixed pixels, cloud cover, and the ability of the sensor to retrieve vegetation
under saturation conditions in high biomass environments. Therefore, an effort
to analyze and quantify the uncertainty of GPP products derived from satellite
platforms is needed. This study quatifies the uncertainty of commonly used
satellite vegetation indices such as Normalized Difference Vegetation Index (NDVI), Enhance
Vegetation Index (EVI), Chlorophyll/Carotenoid Index (CCI), and Near-Infrared Reflectance Index (NIRv)
for GPP estimation compared with direct methods such as EC
measurements. We conduct this study on three different sites: University of
Michigan Biological Station (USA), the Borden Forest Research Station flux-site
(Canada) and Bartlett Experimental Forest (USA) using traditional regression
methods and ML approaches.
