# Assesing uncertanties related to satellite remote sensing indices to estimate
Gross Primary Production 

## Introduction

Gross Primary Production (GPP) is the total amount of carbon fixation by plants
through photosynthesis [@badgley_terrestrial_2019]. Quantifying GPP is essential
for understanding land-atmosphere carbon exchange [@kohler_global_2018],
ecosystem function, and ecosystem responses to climate change
[@guan_comparison_2022; @brown_fiducial_2021; @myneni_relationship_1994].  With
recent advances in technology for remote sensing and more computational power
available with lower costs [@gorelick_google_2017], global mapping of
photosynthesis is being done by more scientists [@ryu_what_2019]. Given that GPP
cannot be directly estimated from satellite remote sensing techniques, the use
of vegetation indices has been a widely used method to approximate and quantify
GPP [@ryu_what_2019]. However, estimates remain with high uncertainties and
validation efforts are required to characterize these and improve accuracy.
[@anav_spatiotemporal_2015; @brown_fiducial_2021]

There are several methods to calculate GPP that can be grouped into two broad
categories: eddy covariance techniques, and satellite data-driven
[@guan_comparison_2022; @xie_assessments_2020] Eddy Covariance (EC) techniques
are methods that allowed scientists to directly measure the carbon, water, and
energy fluxes between vegetation canopies and the atmosphere since the 1990s
[@baldocchi_how_2020; @ryu_what_2019]. This method to measure terrestrial
fluxes, is the principal approach for quantifying the exchange of CO2 between
the land and atmosphere using advanced field instrumentation
[@badgley_terrestrial_2019; @tramontana_predicting_2016]. Measurements provided
using EC have a limited spatial resolution of less than < 1km2 , which bring
spatial constraints to estimations of  ecosystem carbon and water fluxes at
regional to global scales. [@badgley_canopy_2017].   

The second category of methods to estimate GPP is the satellite data-driven
models. Because of their dependency on earth observation platforms, they are not
spatially constrained but can have more uncertainties than the EC techniques
[@ryu_what_2019; @wang_diagnosing_2011]. Satellite data-driven models can be
classified into Vegetation Index models (VI), Light Use Efficiency models (LUE),
and process-based models [@xie_assessments_2020]. 

LUE models are based on the concept of radiation conversion efficiency, and take
into consideration ecological processes [@LIU1997158]. The radiation conversion
efficiency explains the amount of carbon that a specific type of vegetation can
fix per unit of solar radiation [@monteith_solar_1972]. MODIS GPP product uses
an algorithm based on this radiation conversion efficiency concept, relating the
absorbed photosynthetically active radiation (APAR) with the LUE term
[@heinsch_evaluation_2006]. 

GPP = PAR * fAPAR * LUE

Where PAR is the incident photosynthetically active radiation and fAPAR is the
fraction of the PAR that is effectively absorbed by plants. fAPAR can be used to
assess the primary productivity of canopies [GCOS, 2011;
@running_continuous_2004].  LUE is the radiation use conversion efficiency term
of the vegetation [@heinsch_evaluation_2006]

VI’s are a summary of satellite obtained spectral data
[@myneni_relationship_1994] derived from optical sensors that are combined with
climate variables to calculate GPP [@wu_predicting_2011].  This is usually done
with some form of regression and physical methods that associate interactions
between vegetation and incoming radiation [@fernandez-martinez_monitoring_2019]

Well known VI’s used to estimate GPP are normalized difference vegetation index
(NDVI), enhanced vegetation index (EVI), leaf area index (LAI), and fraction of
photosynthetically active radiation (fPAR) among others [@balzarolo_influence_2019; @rahman_potential_2005; @rahman_potential_2005; @xie_assessments_2020; @badgley_terrestrial_2019; @zhang_potential_2020; @sellers_global_1994]

Nonetheless, even when estimating GPP from satellite remote sensing methods is
promising to overcome limitations as temporal and spatial scale, there are some
challenges involved in the process. The first constraint is the use of images
needed to address the problem of mixed-pixels, which requires determining the
fraction of the vegetated surface and its attributable signal [@badgley_canopy_2017]. A second challenge is that photosynthesis regulation can occur with no
major changes in canopy structure or leaf pigments that can undergo without
being detected with reflectance data [@pabon-moreno_potential_2022; @pierrat_diurnal_2022] 

The accuracy of GPP estimation through the use of VI’s can be affected due to
their limitation to predict spatial, temporal, interannual variability and
trends. [@fernandez-martinez_monitoring_2019]. An index such as NDVI is good for
detecting changes in seasonal variability, but it becomes saturated with high
biomass conditions [@badgley_canopy_2017]. Other indices such as EVI can
overcome this problem and be better suited for predicting GPP in large biomass
forests [@badgley_canopy_2017] but it has been evaluated in a narrow range of
ecosystems and needs inputs of start and end dates of the growing seasons which
can increase uncertainties [@shi_assessing_2017]. 

To overcome these problems, other indices have been formulated in recent years.
One of these VIs is near-infrared reflectance index (NIRv) [@badgley_terrestrial_2019] NIRv is defined as the fraction of reflected NIR light that originates
from vegetation. NIRv was originally proposed as a replacement for fPAR in LUE
models in that the NIR and PAR reflectance of vegetation are correlated and the
scaling by NDVI corrects for soil contributions in the signal [@Badgley et al.]  NIRv has been shown to have a stronger correlation to GPP at flux towers
and on a regional basis than fAPAR notwithstanding the fact that GPP is fAPAR
driven.  NIRv has been extended to include a weighting with PAR [@dechant_nirvp_2022] and replacing the NIR reflectance with  NIRv radiance [@wu_radiance-based_2020]. Both of these approaches have been shown to have even stronger correlations with
GPP than NIRv as could be expected since they either directly or indirectly
weight the NIRv with PAR.

The stronger correlation between the NIR indices to GPP versus indices based on
fAPAR seemingly contradicts the hypotheses in the LUE model that GPP should be
linearly related to fAPAR.  There are two explanations: i.  Many of the reported
comparative studies use fAPAR based on VIs and not APAR.  We hypothesize that
the NIR indices are simply better estimators of APAR than these VI
approximations due to lower measurement error for the NIR indices or a stronger
physical relationship between them and APAR versus the historical VIs. The
strength of correlation between APAR and GPP depends on LUE having a linear
relationship to observed APAR.  While this may hold in some circumstances (e.g.
early seasonal measurements for vegetation such as crops where leaf chlorophyll
concentration increases during the growth phase) it is not the case in general
and definitely during stress conditions [@monteith_solar_1972].  

Despite these efforts, relying solely on these remote satellite indices is a
problem. Efforts to validate and quantify their accuracy are needed [@brown_fiducial_2021].  In-situ eddy-covariance flux measurements represent a solution
given that they represent site-level observations. With the calculation of the
flux footprint, the area from the flux tower can serve as a reference point in
which satellite images can be linked to a specific set of pixels and calculate
the accuracy of the estimations provided by the indices. [@chu_representativeness_2021]. 

As such, the main objective of my M.Sc. thesis is the analysis of uncertainty
associated with the VI/LUE models since they offer the potential for GPP
estimation without requiring knowledge regarding canopy and soil properties
other than measurements of reflected light and possibly a correction for soil
contribution. We aim to quantify the uncertainty from some of the most used
satellite vegetation indices with in-situ GPP data from the Santa Rosa National
Park flux-site (Costa Rica), the Borden Forest Research Station flux-site
(Canada), Chamela Biological Station (México)  and a corn/soybean site from
Dechant et al. 2022.

## Methods


The second flux site is Borden Forest Research Station located in Ontario,
Canada. This is one of the largest patches of forest in Southern Ontario which
has been collecting EC data since 1996 (Rogers et al., 2020).  This site has a
forest cover of over 60% with a height that exceeds 2 m. It’s a deciduous
broadleaf natural re-growth forest dominated by woody vegetation. (Lee et al.,
1999).




## Results



## Discussion



